"""empty message

Revision ID: 543d4ca74795
Revises: 5dec196cfd41
Create Date: 2020-07-21 20:23:09.508754

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '543d4ca74795'
down_revision = '5dec196cfd41'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('pass_secure', sa.String(), nullable=True))
    op.drop_column('users', 'password_secure')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password_secure', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('users', 'pass_secure')
    # ### end Alembic commands ###
